### ISSUE TITLE
Unexpected UUID displayed in find properties search result

### ISSUE THREAD

**Issue by knutwannheden** [moderneinc/support-public#13]
When e.g. searching for Java types or annotations the matches are displayed as single diff lines (with both the removed and added lines being equal), which is expected. But when using `org.openrewrite.properties.search.FindProperties` to find specific properties, the result view includes a UUID before and after the value of the matched property, as in the following screenshot:

![image](https://user-images.githubusercontent.com/408765/206041673-55d6380c-e53b-441f-bfa4-cf5ae97c0333.png)

I assume this isn't the expected behavior. See here for an [example](https://public.moderne.io/results/GoFn8/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+c3ByaW5nLWNsb3VkL3NwcmluZy1jbG91ZC1mdW5jdGlvbn5+bWFpbiIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoic3ByaW5nLWNsb3VkL3NwcmluZy1jbG91ZC1mdW5jdGlvbiIsImJyYW5jaCI6Im1haW4iLCJvcmdhbml6YXRpb24iOiJzcHJpbmctY2xvdWQiLCJuYW1lIjoic3ByaW5nLWNsb3VkLWZ1bmN0aW9uIiwiaW5nZXN0ZWQiOm51bGx9?referrer=%2Fresults%2FGoFn8).

**Comment by knutwannheden** [comment]
Seems to be related to #9.

**Comment by zieka** [comment]
Thank you for the example!
It looks like the marker data is coming back empty on that run 🤔:

![Image](https://user-images.githubusercontent.com/4691147/206261829-935f0937-2448-4371-85f6-9742ef60dc05.png)


I'll replicate locally and let you know what I find.

**Comment by zieka** [comment]
It look like when we override `visitMarker` to accumulate the diffs in our worker we are not picking up the markers attached to `Properties.Value`.  It looks like the visitor is not visiting those markers.  At one point they were but it looks like it was deliberatively changed: 
https://github.com/openrewrite/rewrite/commit/09ba3895ee40d1f25c16b57f0cebfcf797bfb441#diff-5dbc935f7f875bb442cd092016cccdd8656e7e2b21d8f08613532a53eef1168dL45

**Comment by zieka** [comment]
related https://github.com/openrewrite/rewrite/pull/2523

**Comment by zieka** [comment]
I can confirm that the underlying issue is now resolved.  

I tried running on the old artifact but it results in an error: https://github.com/openrewrite/rewrite/issues/2607

`spring-cloud/spring-cloud-function` will need to be re-ingested to obtain a new artifact.

**Comment by knutwannheden** [comment]
@zieka Yes, I can also confirm that it works now. I was however a little bit surprised, that the search result highlights the property value rather than the property name. Please let me know if this is a bug and you would like me to report a separate issue for this.

![image](https://user-images.githubusercontent.com/408765/211216924-bd537e31-7d52-4511-ae77-f023022672a5.png)

**Comment by knutwannheden** [comment]
And what I suspect may be a related issue is the fact that the properties core recipes don't appear to work. While I can find the `org.slf4j.simpleLogger.showShortLogName` property in the Netflix/astyanax repo, I cannot get the delete or change property key or value recipes to find that property.

If the underlying issue is in the OpenRewrite repo, I can report the issue there.

**Comment by zieka** [comment]
> I cannot get the delete or change property key or value recipes to find that property.

When you try these recipes there is a file path matcher, could you try with `**/*`.  I think this is a separate issue with a fix coming soon.

**Comment by knutwannheden** [comment]
Yes, you are right: Specifying the "optional" file matcher indeed appears to be the solution.

Any thoughts regarding the question with the highlighting of the property value as opposed to the key? Although, that is rather cosmetic.
