### ISSUE TITLE
🐛 UnknownError Internal error. UnknownError: Internal error.

### ISSUE THREAD

**Issue by Rajpratik71** [moderneinc/support-public#47]
```
DatabaseClosedError: UnknownError Internal error.
 UnknownError: Internal error.
    at e (https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:59155)
    at https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:59342
    at https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:57129
    at eA (https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:51981)
    at e$ (https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:52465)
    at IDBOpenDBRequest.<anonymous> (https://public.moderne.io/_next/static/chunks/pages/_app-277d4900eecab404.js:197:52823)
```

https://public.moderne.io/

**Comment by timtebeek** [comment]
Sorry to hear about this issue @Rajpratik71 ; Could you provide us with some context to what you were doing when this error popped up?

**Comment by Rajpratik71** [comment]
After github login callback and redirect to https://public.moderne.io/ this is happening

**Comment by Rajpratik71** [comment]
Even at https://app.moderne.io/

**Comment by timtebeek** [comment]
That's weird; I'm having no such issues logging in to either of those; I'll pass your note along to the team!

**Comment by natedanner** [comment]
@Rajpratik71 Sorry to hear about your login issue. Can you provide the operating system and browser you are using?

**Comment by Rajpratik71** [comment]
Browser:

`Version 113.0.5672.92 (Official Build) (64-bit)`

OS:

`Linux workplace-Latitude-5420 5.15.0-72-generic #79~20.04.1-Ubuntu SMP Thu Apr 20 22:12:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by natedanner** [comment]
@Rajpratik71 Are you running in incognito mode or have any plugins that might block indexedDB? I suggest clearing your browser storage for the site from dev tools and trying again. 
![Screenshot 2023-06-09 at 1 53 52 PM](https://github.com/moderneinc/support-public/assets/882752/b507e255-5966-47ca-b8fe-93d2cc16c239)
