### ISSUE TITLE
org.junit.Test import left behind

### ISSUE THREAD

**Issue by jkschneider** [moderneinc/support-public#6]
### Example diff
```diff
    import org.eclipse.jgit.api.Git;
import org.junit.Test;

-import static junit.framework.Assert.assertNotNull;
+import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
* @since version
   ```

#### Recipes in example diff:
- `org.openrewrite.java.testing.junit5.MigrateJUnitTestCase`

### References:
- [View original result](https://public.moderne.io/results/UDJZ5/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+VGFuZW1haHV0YS9ncmFkbGUtdmdmci1wbHVnaW5+fmRldmVsb3BtZW50Iiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJUYW5lbWFodXRhL2dyYWRsZS12Z2ZyLXBsdWdpbiIsImJyYW5jaCI6ImRldmVsb3BtZW50Iiwib3JnYW5pemF0aW9uIjoiVGFuZW1haHV0YSIsIm5hbWUiOiJncmFkbGUtdmdmci1wbHVnaW4iLCJpbmdlc3RlZCI6bnVsbH0=)
- Recipe ID: `org.openrewrite.java.testing.junit5.MigrateJUnitTestCase`
- Recipe Name: `undefined`
- Repository: `Tanemahuta/gradle-vgfr-plugin/development`
- Created at Wed Oct 12 2022 03:18:05 GMT-0700 (Pacific Daylight Time)

**Comment by jkschneider** [comment]
### Example diff
```diff
    import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.startsWith;
import static org.hamcrest.MatcherAssert.assertThat;
-import static org.junit.Assert.*;
+import static org.junit.jupiter.api.Assertions.*;
import static picocli.CommandLine.*;
import static picocli.CommandLine.Model.UsageMessageSpec.keyValuesMap;

   ```
```diff
        for (IExecutionStrategy strategy : strategies) {
      String descr = strategy.getClass().getSimpleName();
      int actual = factory.create().setExecutionStrategy(strategy).execute(args);
-            assertEquals(descr + ": return value", expected, actual);
+            assertEquals(expected, actual, descr + ": return value");
  }
}
```

#### Recipes in example diff:
- `org.openrewrite.java.testing.junit5.AssertToAssertions`

### References:
- [View original result](https://public.moderne.io/results/nNdYZ/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+cmVta29wL3BpY29jbGl+fm1haW4iLCJvcmlnaW4iOiJnaXRodWIuY29tIiwicGF0aCI6InJlbWtvcC9waWNvY2xpIiwiYnJhbmNoIjoibWFpbiIsIm9yZ2FuaXphdGlvbiI6InJlbWtvcCIsIm5hbWUiOiJwaWNvY2xpIiwiaW5nZXN0ZWQiOm51bGx9)
- Recipe ID: `org.openrewrite.java.testing.junit5.AssertToAssertions`
- Recipe Name: `undefined`
- Repository: `remkop/picocli/main`
- Created at Wed Oct 12 2022 03:54:23 GMT-0700 (Pacific Daylight Time)

**Comment by jkschneider** [comment]
### Example diff
```diff
 
package com.graphicsfuzz.common.ast.expr;

-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertFalse;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertFalse;

import org.junit.Before;
import org.junit.Test;
```

#### Recipes in example diff:
- `org.openrewrite.java.testing.junit5.AssertToAssertions`

### References:
- [View original result](https://public.moderne.io/results/nNdYZ/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+Z29vZ2xlL2dyYXBoaWNzZnV6en5+bWFzdGVyIiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJnb29nbGUvZ3JhcGhpY3NmdXp6IiwiYnJhbmNoIjoibWFzdGVyIiwib3JnYW5pemF0aW9uIjoiZ29vZ2xlIiwibmFtZSI6ImdyYXBoaWNzZnV6eiIsImluZ2VzdGVkIjpudWxsfQ==)
- Recipe ID: `org.openrewrite.java.testing.junit5.AssertToAssertions`
- Recipe Name: `undefined`
- Repository: `google/graphicsfuzz/master`
- Created at Wed Oct 12 2022 04:06:37 GMT-0700 (Pacific Daylight Time)

**Comment by okundzich** [comment]
needs to be transferred to rewrite? @sambsnyd
