### ISSUE TITLE
StackOverflowError in isWellFormedType

### ISSUE THREAD

**Issue by jkschneider** [moderneinc/support-public#7]
### Example diff
```diff
        /* empty */
}

-    public static class SampleGenericType<T extends ArrayList<T> & Callable<T>,
+    public static class /*~~(Recipe failed with an exception.
+java.lang.StackOverflowError: null
+  java.base/java.util.HashMap.putVal(HashMap.java:627)
+  java.base/java.util.HashMap.put(HashMap.java:610)
+  java.base/java.util.HashSet.add(HashSet.java:221)
+  org.openrewrite.java.tree.TypeUtils.isWellFormedType(TypeUtils.java:388)
+  org.openrewrite.java.tree.TypeUtils.isWellFormedType(TypeUtils.java:381)
+  org.openrewrite.java.tree.TypeUtils.isWellFormedType(TypeUtils.java:391)
+  org.openrewrite.java.tree.TypeUtils.lambda$isWellFormedType$4(TypeUtils.java:397)
+  java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
+  ...)~~>*/SampleGenericType<T extends ArrayList<T> & Callable<T>,
      S extends Callable<?>,
      U extends Callable<? extends Callable<U>>,
      V extends ArrayList<? super ArrayList<V>>,
```

#### Recipes in example diff:
- `org.openrewrite.java.testing.mockito.CleanupMockitoImports`

### References:
- [View original result](https://public.moderne.io/results/nNdYZ/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+cmFwaHcvYnl0ZS1idWRkeX5+bWFzdGVyIiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJyYXBody9ieXRlLWJ1ZGR5IiwiYnJhbmNoIjoibWFzdGVyIiwib3JnYW5pemF0aW9uIjoicmFwaHciLCJuYW1lIjoiYnl0ZS1idWRkeSIsImluZ2VzdGVkIjpudWxsfQ==)
- Recipe ID: `org.openrewrite.java.testing.mockito.CleanupMockitoImports`
- Recipe Name: `undefined`
- Repository: `raphw/byte-buddy/master`
- Created at Wed Oct 12 2022 03:57:41 GMT-0700 (Pacific Daylight Time)

**Comment by jkschneider** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1697736/195325446-068447c9-0c96-4f6f-bc70-604e687d0bda.png">

**Comment by okundzich** [comment]
needs to be transferred to rewrite? @sambsnyd
