### ISSUE TITLE
Issue discovered with `Change type`

### ISSUE THREAD

**Issue by kmccarp** [moderneinc/support-public#8]
### Problem
Java "Change type" recipe throws the following exception.

### Example diff

From moderne code:

```diff
-package io.moderne.worker;
+/*~~(Recipe failed with an exception.
+java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
+  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
+  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
+  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
+  java.base/java.util.Objects.checkIndex(Objects.java:359)
+  java.base/java.util.ArrayList.get(ArrayList.java:427)
+  org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:247)
+  org.openrewrite.java.internal.template.JavaTemplateParser.lambda$parsePackage$8(JavaTemplateParser.java:217)
+  org.openrewrite.java.internal.template.JavaTemplateParser.cache(JavaTemplateParser.java:256)
+  ...)~~>*/package io.moderne.worker;

```

#### Recipes in example diff:
- `org.openrewrite.java.ChangeType`

### References:
- [View original result](https://public.moderne.io/results/MXCzq/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+bW9kZXJuZWluYy9tb2Rlcm5lLXdvcmtlci1tb2RlbH5+bWFpbiIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoibW9kZXJuZWluYy9tb2Rlcm5lLXdvcmtlci1tb2RlbCIsImJyYW5jaCI6Im1haW4iLCJvcmdhbml6YXRpb24iOiJtb2Rlcm5laW5jIiwibmFtZSI6Im1vZGVybmUtd29ya2VyLW1vZGVsIiwiaW5nZXN0ZWQiOm51bGx9)
- Recipe ID: `org.openrewrite.java.ChangeType`
- Recipe Name: `Change type`
- Repository: `moderneinc/moderne-worker-model/main`
- Created at Mon Oct 17 2022 17:27:34 GMT-0300 (Horário Padrão da Argentina)

**Comment by sambsnyd** [comment]
![image](https://user-images.githubusercontent.com/8549033/196286215-6cd0c0bc-6443-4093-bb66-c368d2cd2f64.png)

**Comment by okundzich** [comment]
Is this a rewrite issue or Moderne SaaS issue? @sambsnyd @kmccarp

**Comment by kmccarp** [comment]
I believe it's a Rewrite issue - the array index out of bounds happened in rewrite code.

**Comment by okundzich** [comment]
@sambsnyd please transfer. I don't see an easy way to do so.

**Comment by sjungling** [comment]
fwiw I'm not sure it's presently possible to transfer issues across GitHub organizations
https://github.com/community/community/discussions/5766
