### ISSUE TITLE
Issue discovered on Spring Boot 2.7 recipe

### ISSUE THREAD

**Issue by jkschneider** [moderneinc/support-public#9]
### Example diff

**From:** `deployment/src/test/resources/openapi/issue-28.yaml`

```diff
   #

"/api/connector_mgmt/v1/kafka_connector_types/{connector_type_id}":
-    parameters:
+    {{cae459c6-7c26-4d39-90b7-8d345c599adb}}parameters:
 - name: connector_type_id
   description: The id of the connector type
   schema:
     type: string
   in: path
-        required: true
+        required: true{{cae459c6-7c26-4d39-90b7-8d345c599adb}}
get:
 tags:
   - Connector Types
```

#### Recipes in example diff:
- `org.openrewrite.yaml.ChangePropertyKey`

### References:
- [View original result](https://public.moderne.io/results/EYRp9/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+cXVhcmtpdmVyc2UvcXVhcmt1cy1vcGVuYXBpLWdlbmVyYXRvcn5+bWFpbiIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoicXVhcmtpdmVyc2UvcXVhcmt1cy1vcGVuYXBpLWdlbmVyYXRvciIsImJyYW5jaCI6Im1haW4iLCJvcmdhbml6YXRpb24iOiJxdWFya2l2ZXJzZSIsIm5hbWUiOiJxdWFya3VzLW9wZW5hcGktZ2VuZXJhdG9yIiwiaW5nZXN0ZWQiOm51bGx9)
- Recipe ID: `org.openrewrite.yaml.ChangePropertyKey`
- Recipe Name: `Change property key`
- Repository: `quarkiverse/quarkus-openapi-generator/main`
- Created at Wed Oct 19 2022 10:40:11 GMT-0700 (Pacific Daylight Time)

**Comment by okundzich** [comment]
@jkschneider  @zieka what kind of issue this is? Marker?

**Comment by kmccarp** [comment]
Ran the spring boot 2.7 upgrade on this repo and got no errors: https://public.moderne.io/results/QV2l6

Going to close this issue.
